### PR TITLE
Add serial config

### PR DESCRIPTION
**Pull request by danielcharrua**
On restart if GPIO is touched the device will enter on "serial config mode".
Also added a .gitignore to work more comfortable with vscode and Mac when pushing changes.

### CODE REVIEW

**Comment by AxelHamburch** [comment]
I have tested it, it works. Pin 4 to activate the "Launch portal" or now "Launch serial config" was the missing access.

**Comment by AxelHamburch** [comment]
It does not work, you have to choose another variant.

**Comment by danielcharrua** [comment]
@AxelHamburch can you explain? This PR adds an old feature that was deprecated (I think @arcbtc explained why in the telegram group). When I touch pin 4 the device enters in serial config mode, but this has nothing to do with the browser serial.

If this PR is not addressing the issue you can discard it, no worries!

**Comment by arcbtc** [comment]
I deleted this code, because it does nothing, only get in the way of using gpio4

**Comment by danielcharrua** [comment]
@arcbtc how do you load the json config if not enabling the serial config mode on the device? We were talking these past days on Telegram but nobody answered that 🫠

**Comment by arcbtc** [comment]
I'd like @motorina0 to take a look, as I think the fix is the memory gets wiped before uploading new config. As far as I am aware this code is redundant.

**Comment by motorina0** [comment]
@danielcharrua I need a bit of help here. Can you please specify:

### Summary
 - what the problem was
 
**Steps**:
 1. start the device...
 2. ....

**Actual Result**:
 - ...

**Expected Result**:
 - ... (what this fix does)

**Review by dni — APPROVED** [review]

**Pull request merged**
